"""empty message

Revision ID: 0f8ea7c7e50a
Revises: 528decc4e708
Create Date: 2026-01-20 00:21:08.830504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f8ea7c7e50a'
down_revision: Union[str, Sequence[str], None] = '528decc4e708'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lesson_level', sa.Column('language_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('lesson_level_user_id_course_id_key'), 'lesson_level', type_='unique')
    op.create_unique_constraint(None, 'lesson_level', ['user_id', 'language_id'])
    op.drop_constraint(op.f('lesson_level_course_id_fkey'), 'lesson_level', type_='foreignkey')
    op.create_foreign_key(None, 'lesson_level', 'language', ['language_id'], ['id'])
    op.drop_column('lesson_level', 'course_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lesson_level', sa.Column('course_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'lesson_level', type_='foreignkey')
    op.create_foreign_key(op.f('lesson_level_course_id_fkey'), 'lesson_level', 'course', ['course_id'], ['id'])
    op.drop_constraint(None, 'lesson_level', type_='unique')
    op.create_unique_constraint(op.f('lesson_level_user_id_course_id_key'), 'lesson_level', ['user_id', 'course_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('lesson_level', 'language_id')
    # ### end Alembic commands ###
