"""empty message

Revision ID: 4d36ea8a8caf
Revises: db9d2f8beebf
Create Date: 2026-01-20 01:06:36.757412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d36ea8a8caf'
down_revision: Union[str, Sequence[str], None] = 'db9d2f8beebf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('language_progress_user_id_language_id_key'), 'language_progress', type_='unique')
    op.create_unique_constraint('uq_user_language', 'language_progress', ['user_id', 'language_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_language', 'language_progress', type_='unique')
    op.create_unique_constraint(op.f('language_progress_user_id_language_id_key'), 'language_progress', ['user_id', 'language_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
