"""empty message

Revision ID: 9741125b1359
Revises: 
Create Date: 2026-01-25 13:38:31.758183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9741125b1359'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('achievement',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_achievement_code'), 'achievement', ['code'], unique=True)
    op.create_index(op.f('ix_achievement_title'), 'achievement', ['title'], unique=True)
    op.create_table('family_follow',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('language',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_language_code'), 'language', ['code'], unique=True)
    op.create_index(op.f('ix_language_name'), 'language', ['name'], unique=True)
    op.create_table('max_follow',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profile',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('avatar', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=60), nullable=True),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('role', sa.Enum('user', 'admin', name='rolechoices'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('date_register', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profile_date_register'), 'profile', ['date_register'], unique=False)
    op.create_index(op.f('ix_profile_email'), 'profile', ['email'], unique=True)
    op.create_index(op.f('ix_profile_username'), 'profile', ['username'], unique=True)
    op.create_table('super_follow',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('add_friends',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_add_friends_user_id'), 'add_friends', ['user_id'], unique=False)
    op.create_table('country',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_country_user_id'), 'country', ['user_id'], unique=False)
    op.create_table('course',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('language_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('level', sa.Enum('A1', 'A2', 'B1', 'B2', 'C1', 'C2', name='levelchoices'), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['language_id'], ['language.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_course_language_id'), 'course', ['language_id'], unique=False)
    op.create_table('follow',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('following_id', sa.Integer(), nullable=False),
    sa.Column('follower_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['follower_id'], ['profile.id'], ),
    sa.ForeignKeyConstraint(['following_id'], ['profile.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('following_id', 'follower_id', name='uq_follow_pair')
    )
    op.create_index(op.f('ix_follow_follower_id'), 'follow', ['follower_id'], unique=False)
    op.create_index('ix_follow_following_follower', 'follow', ['following_id', 'follower_id'], unique=False)
    op.create_index(op.f('ix_follow_following_id'), 'follow', ['following_id'], unique=False)
    op.create_table('group',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=False),
    sa.Column('is_private', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_group_create_date'), 'group', ['create_date'], unique=False)
    op.create_index(op.f('ix_group_owner_id'), 'group', ['owner_id'], unique=False)
    op.create_table('history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('xp', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_history_created_date'), 'history', ['created_date'], unique=False)
    op.create_index('ix_history_user_created', 'history', ['user_id', 'created_date'], unique=False)
    op.create_index(op.f('ix_history_user_id'), 'history', ['user_id'], unique=False)
    op.create_table('refresh_token',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_token_created_date'), 'refresh_token', ['created_date'], unique=False)
    op.create_index(op.f('ix_refresh_token_token'), 'refresh_token', ['token'], unique=True)
    op.create_index(op.f('ix_refresh_token_user_id'), 'refresh_token', ['user_id'], unique=False)
    op.create_table('streak',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('current_steak', sa.Integer(), nullable=False),
    sa.Column('last_activity', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_streak_user_id'), 'streak', ['user_id'], unique=False)
    op.create_table('user_achievement',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('achievement_id', sa.Integer(), nullable=False),
    sa.Column('date_received', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['achievement_id'], ['achievement.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['profile.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'achievement_id', name='uq_user_achievement_user_achievement')
    )
    op.create_index(op.f('ix_user_achievement_achievement_id'), 'user_achievement', ['achievement_id'], unique=False)
    op.create_index(op.f('ix_user_achievement_date_received'), 'user_achievement', ['date_received'], unique=False)
    op.create_index('ix_user_achievement_user_achievement', 'user_achievement', ['user_id', 'achievement_id'], unique=False)
    op.create_index(op.f('ix_user_achievement_user_id'), 'user_achievement', ['user_id'], unique=False)
    op.create_table('chat_read_state',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('last_read_message_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['profile.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'user_id', name='uq_read_state_group_user')
    )
    op.create_index(op.f('ix_chat_read_state_group_id'), 'chat_read_state', ['group_id'], unique=False)
    op.create_index(op.f('ix_chat_read_state_updated_at'), 'chat_read_state', ['updated_at'], unique=False)
    op.create_index(op.f('ix_chat_read_state_user_id'), 'chat_read_state', ['user_id'], unique=False)
    op.create_index('ix_read_state_group_user', 'chat_read_state', ['group_id', 'user_id'], unique=False)
    op.create_table('lesson',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('is_locked', sa.Boolean(), nullable=False),
    sa.Column('xp_reward', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lesson_course_id'), 'lesson', ['course_id'], unique=False)
    op.create_table('message',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('edited_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_created_date'), 'message', ['created_date'], unique=False)
    op.create_index('ix_message_group_created', 'message', ['group_id', 'created_date'], unique=False)
    op.create_index(op.f('ix_message_group_id'), 'message', ['group_id'], unique=False)
    op.create_index(op.f('ix_message_is_deleted'), 'message', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_message_user_id'), 'message', ['user_id'], unique=False)
    op.create_table('people',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('joined_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['profile.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'user_id', name='uq_people_group_user')
    )
    op.create_index(op.f('ix_people_group_id'), 'people', ['group_id'], unique=False)
    op.create_index('ix_people_group_user', 'people', ['group_id', 'user_id'], unique=False)
    op.create_index(op.f('ix_people_user_id'), 'people', ['user_id'], unique=False)
    op.create_table('rating',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('streak_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['streak_id'], ['streak.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rating_streak_id'), 'rating', ['streak_id'], unique=False)
    op.create_index(op.f('ix_rating_user_id'), 'rating', ['user_id'], unique=False)
    op.create_table('exercise',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('A1', 'A2', 'B1', 'B2', 'C1', 'C2', name='levelchoices'), nullable=False),
    sa.Column('questions', sa.Text(), nullable=False),
    sa.Column('correct_answer', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lesson.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exercise_lesson_id'), 'exercise', ['lesson_id'], unique=False)
    op.create_table('lesson_completion',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('date_completed', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lesson.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['profile.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'lesson_id', name='user_lesson_unique')
    )
    op.create_index(op.f('ix_lesson_completion_date_completed'), 'lesson_completion', ['date_completed'], unique=False)
    op.create_index(op.f('ix_lesson_completion_lesson_id'), 'lesson_completion', ['lesson_id'], unique=False)
    op.create_index(op.f('ix_lesson_completion_user_id'), 'lesson_completion', ['user_id'], unique=False)
    op.create_index('ix_lesson_completion_user_lesson', 'lesson_completion', ['user_id', 'lesson_id'], unique=False)
    op.create_table('lesson_level',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), server_default='1', nullable=False),
    sa.Column('experience', sa.Integer(), server_default='0', nullable=False),
    sa.Column('max_level', sa.Integer(), server_default='100', nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lesson.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['profile.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'lesson_id', name='uq_lesson_level_user_lesson')
    )
    op.create_index(op.f('ix_lesson_level_lesson_id'), 'lesson_level', ['lesson_id'], unique=False)
    op.create_index(op.f('ix_lesson_level_user_id'), 'lesson_level', ['user_id'], unique=False)
    op.create_index('ix_lesson_level_user_lesson', 'lesson_level', ['user_id', 'lesson_id'], unique=False)
    op.create_table('user_progress',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('xp_earned', sa.Integer(), nullable=False),
    sa.Column('completed_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lesson.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['profile.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'lesson_id', name='uq_user_progress_user_lesson')
    )
    op.create_index(op.f('ix_user_progress_completed_date'), 'user_progress', ['completed_date'], unique=False)
    op.create_index(op.f('ix_user_progress_lesson_id'), 'user_progress', ['lesson_id'], unique=False)
    op.create_index(op.f('ix_user_progress_user_id'), 'user_progress', ['user_id'], unique=False)
    op.create_index('ix_user_progress_user_lesson', 'user_progress', ['user_id', 'lesson_id'], unique=False)
    op.create_table('option',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercise.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_option_exercise_id'), 'option', ['exercise_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_option_exercise_id'), table_name='option')
    op.drop_table('option')
    op.drop_index('ix_user_progress_user_lesson', table_name='user_progress')
    op.drop_index(op.f('ix_user_progress_user_id'), table_name='user_progress')
    op.drop_index(op.f('ix_user_progress_lesson_id'), table_name='user_progress')
    op.drop_index(op.f('ix_user_progress_completed_date'), table_name='user_progress')
    op.drop_table('user_progress')
    op.drop_index('ix_lesson_level_user_lesson', table_name='lesson_level')
    op.drop_index(op.f('ix_lesson_level_user_id'), table_name='lesson_level')
    op.drop_index(op.f('ix_lesson_level_lesson_id'), table_name='lesson_level')
    op.drop_table('lesson_level')
    op.drop_index('ix_lesson_completion_user_lesson', table_name='lesson_completion')
    op.drop_index(op.f('ix_lesson_completion_user_id'), table_name='lesson_completion')
    op.drop_index(op.f('ix_lesson_completion_lesson_id'), table_name='lesson_completion')
    op.drop_index(op.f('ix_lesson_completion_date_completed'), table_name='lesson_completion')
    op.drop_table('lesson_completion')
    op.drop_index(op.f('ix_exercise_lesson_id'), table_name='exercise')
    op.drop_table('exercise')
    op.drop_index(op.f('ix_rating_user_id'), table_name='rating')
    op.drop_index(op.f('ix_rating_streak_id'), table_name='rating')
    op.drop_table('rating')
    op.drop_index(op.f('ix_people_user_id'), table_name='people')
    op.drop_index('ix_people_group_user', table_name='people')
    op.drop_index(op.f('ix_people_group_id'), table_name='people')
    op.drop_table('people')
    op.drop_index(op.f('ix_message_user_id'), table_name='message')
    op.drop_index(op.f('ix_message_is_deleted'), table_name='message')
    op.drop_index(op.f('ix_message_group_id'), table_name='message')
    op.drop_index('ix_message_group_created', table_name='message')
    op.drop_index(op.f('ix_message_created_date'), table_name='message')
    op.drop_table('message')
    op.drop_index(op.f('ix_lesson_course_id'), table_name='lesson')
    op.drop_table('lesson')
    op.drop_index('ix_read_state_group_user', table_name='chat_read_state')
    op.drop_index(op.f('ix_chat_read_state_user_id'), table_name='chat_read_state')
    op.drop_index(op.f('ix_chat_read_state_updated_at'), table_name='chat_read_state')
    op.drop_index(op.f('ix_chat_read_state_group_id'), table_name='chat_read_state')
    op.drop_table('chat_read_state')
    op.drop_index(op.f('ix_user_achievement_user_id'), table_name='user_achievement')
    op.drop_index('ix_user_achievement_user_achievement', table_name='user_achievement')
    op.drop_index(op.f('ix_user_achievement_date_received'), table_name='user_achievement')
    op.drop_index(op.f('ix_user_achievement_achievement_id'), table_name='user_achievement')
    op.drop_table('user_achievement')
    op.drop_index(op.f('ix_streak_user_id'), table_name='streak')
    op.drop_table('streak')
    op.drop_index(op.f('ix_refresh_token_user_id'), table_name='refresh_token')
    op.drop_index(op.f('ix_refresh_token_token'), table_name='refresh_token')
    op.drop_index(op.f('ix_refresh_token_created_date'), table_name='refresh_token')
    op.drop_table('refresh_token')
    op.drop_index(op.f('ix_history_user_id'), table_name='history')
    op.drop_index('ix_history_user_created', table_name='history')
    op.drop_index(op.f('ix_history_created_date'), table_name='history')
    op.drop_table('history')
    op.drop_index(op.f('ix_group_owner_id'), table_name='group')
    op.drop_index(op.f('ix_group_create_date'), table_name='group')
    op.drop_table('group')
    op.drop_index(op.f('ix_follow_following_id'), table_name='follow')
    op.drop_index('ix_follow_following_follower', table_name='follow')
    op.drop_index(op.f('ix_follow_follower_id'), table_name='follow')
    op.drop_table('follow')
    op.drop_index(op.f('ix_course_language_id'), table_name='course')
    op.drop_table('course')
    op.drop_index(op.f('ix_country_user_id'), table_name='country')
    op.drop_table('country')
    op.drop_index(op.f('ix_add_friends_user_id'), table_name='add_friends')
    op.drop_table('add_friends')
    op.drop_table('super_follow')
    op.drop_index(op.f('ix_profile_username'), table_name='profile')
    op.drop_index(op.f('ix_profile_email'), table_name='profile')
    op.drop_index(op.f('ix_profile_date_register'), table_name='profile')
    op.drop_table('profile')
    op.drop_table('max_follow')
    op.drop_index(op.f('ix_language_name'), table_name='language')
    op.drop_index(op.f('ix_language_code'), table_name='language')
    op.drop_table('language')
    op.drop_table('family_follow')
    op.drop_index(op.f('ix_achievement_title'), table_name='achievement')
    op.drop_index(op.f('ix_achievement_code'), table_name='achievement')
    op.drop_table('achievement')
    # ### end Alembic commands ###
