"""empty message

Revision ID: ebffcc55b66e
Revises: 4d36ea8a8caf
Create Date: 2026-01-20 01:24:56.371904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebffcc55b66e'
down_revision: Union[str, Sequence[str], None] = '4d36ea8a8caf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('language_progress',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('language_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), server_default='1', nullable=False),
    sa.Column('experience', sa.Integer(), server_default='0', nullable=False),
    sa.Column('max_level', sa.Integer(), server_default='100', nullable=False),
    sa.ForeignKeyConstraint(['language_id'], ['language.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['profile.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'language_id', name='uq_user_language')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('language_progress')
    # ### end Alembic commands ###
