"""empty message

Revision ID: f1cae4207cf1
Revises: 086e8ee37218
Create Date: 2026-01-19 02:40:55.169819

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1cae4207cf1'
down_revision: Union[str, Sequence[str], None] = '086e8ee37218'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lesson_level', sa.Column('course_id', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'lesson_level', ['user_id', 'course_id'])
    op.drop_constraint(op.f('lesson_level_lesson_id_fkey'), 'lesson_level', type_='foreignkey')
    op.create_foreign_key(None, 'lesson_level', 'course', ['course_id'], ['id'])
    op.drop_column('lesson_level', 'lesson_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lesson_level', sa.Column('lesson_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'lesson_level', type_='foreignkey')
    op.create_foreign_key(op.f('lesson_level_lesson_id_fkey'), 'lesson_level', 'lesson', ['lesson_id'], ['id'])
    op.drop_constraint(None, 'lesson_level', type_='unique')
    op.drop_column('lesson_level', 'course_id')
    # ### end Alembic commands ###
